# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cache_fu}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Wanstrath"]
  s.date = %q{2009-08-18}
  s.description = %q{DESCRIPTION!}
  s.email = %q{chris@ozmm.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "CHANGELOG",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "cache_fu.gemspec",
     "defaults/extensions.rb.default",
     "defaults/memcached.yml.default",
     "defaults/memcached_ctl.default",
     "lib/acts_as_cached.rb",
     "lib/acts_as_cached/benchmarking.rb",
     "lib/acts_as_cached/cache_methods.rb",
     "lib/acts_as_cached/config.rb",
     "lib/acts_as_cached/disabled.rb",
     "lib/acts_as_cached/fragment_cache.rb",
     "lib/acts_as_cached/local_cache.rb",
     "lib/acts_as_cached/memcached_rails.rb",
     "lib/acts_as_cached/recipes.rb",
     "lib/cache_fu.rb",
     "tasks/memcached.rake",
     "test/benchmarking_test.rb",
     "test/cache_test.rb",
     "test/config_test.rb",
     "test/disabled_test.rb",
     "test/extensions_test.rb",
     "test/fragment_cache_test.rb",
     "test/helper.rb",
     "test/local_cache_test.rb",
     "test/sti_test.rb"
  ]
  s.homepage = %q{http://github.com/defunkt/cache_fu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{Summarize your gem}
  s.test_files = [
    "test/sti_test.rb",
     "test/benchmarking_test.rb",
     "test/local_cache_test.rb",
     "test/config_test.rb",
     "test/extensions_test.rb",
     "test/fragment_cache_test.rb",
     "test/disabled_test.rb",
     "test/cache_test.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
